/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeKullaniciFavoriteResponseDizi } from './geKullaniciFavoriteResponseDizi';
import { GeKullaniciFavoriteResponseFilm } from './geKullaniciFavoriteResponseFilm';

export interface AuthenticationGirisResponse { 
    token?: string;
    id?: number;
    name?: string;
    surname?: string;
    email?: string;
    role?: AuthenticationGirisResponse.RoleEnum;
    favoriDiziler?: Array<GeKullaniciFavoriteResponseDizi>;
    favoriFilmler?: Array<GeKullaniciFavoriteResponseFilm>;
}
export namespace AuthenticationGirisResponse {
    export type RoleEnum = 'ADMIN' | 'NORMAL';
    export const RoleEnum = {
        ADMIN: 'ADMIN' as RoleEnum,
        NORMAL: 'NORMAL' as RoleEnum
    };
}