/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BolumResponse } from './bolumResponse';

export interface DiziResponse { 
    id?: number;
    name?: string;
    konu?: string;
    yili?: string;
    yonetmen?: string;
    kapakPath?: string;
    fragmanPath?: string;
    bolumler?: Array<BolumResponse>;
    diziCategoryDkid?: number;
}