/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface KullaniciKayitRequests { 
    name?: string;
    surname?: string;
    email?: string;
    sifre?: string;
    role?: KullaniciKayitRequests.RoleEnum;
    geciciDogrulamaKodu?: string;
}
export namespace KullaniciKayitRequests {
    export type RoleEnum = 'ADMIN' | 'NORMAL';
    export const RoleEnum = {
        ADMIN: 'ADMIN' as RoleEnum,
        NORMAL: 'NORMAL' as RoleEnum
    };
}